// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-audio-tracks.mjs

export const audioTracks = [
  {
    title: "CAROUSEL",
    artist: "ANTTIPARK",
    src: "/audio/ANTTIPARK_CAROUSEL.mp3",
  },
  {
    title: "FASTLANE",
    artist: "ANTTIPARK",
    src: "/audio/ANTTIPARK_FASTLANE.mp3",
  },
  {
    title: "KYOTO",
    artist: "ANTTIPARK",
    src: "/audio/ANTTIPARK_KYOTO.mp3",
  },
  {
    title: "REMOTE",
    artist: "ANTTIPARK",
    src: "/audio/ANTTIPARK_REMOTE.mp3",
  },
  {
    title: "SPACETIME",
    artist: "ANTTIPARK",
    src: "/audio/ANTTIPARK_SPACETIME.mp3",
  },
  {
    title: "TEMPORARY",
    artist: "ANTTIPARK",
    src: "/audio/ANTTIPARK_TEMPORARY.mp3",
  },
] as const;
