// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-reel-videos.mjs

export const reelVideos = [
  {
    id: "1",
    src: "/media/ARCLAB_MP4.mp4",
    title: "ARCLAB",
  },
  {
    id: "2",
    src: "/media/CONCEPTS_MP4.mp4",
    title: "CONCEPTS",
  },
  {
    id: "3",
    src: "/media/DANCEMEUP_MP4.mp4",
    title: "DANCEMEUP",
  },
  {
    id: "4",
    src: "/media/DOM_MP4.mp4",
    title: "DOM",
  },
  {
    id: "5",
    src: "/media/H%26K_MP4.mp4",
    title: "H&K",
  },
  {
    id: "6",
    src: "/media/KLANGI_MP4.mp4",
    title: "KLANGI",
  },
];
