// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-reel-videos.mjs

export const reelVideos = [
  {
    id: "1",
    src: "/media/optimized/ARCLAB_MP4.mp4",
    srcHigh: "/media/ARCLAB_MP4.mp4",
    poster: "/media/optimized/ARCLAB_MP4.jpg",
    title: "ARC LAB",
  },
  {
    id: "2",
    src: "/media/optimized/CONCEPTS_MP4.mp4",
    srcHigh: "/media/CONCEPTS_MP4.mp4",
    srcFull: "/media/full/CONCEPTS_MP4.mp4",
    poster: "/media/optimized/CONCEPTS_MP4.jpg",
    title: "CONCEPTS",
  },
  {
    id: "3",
    src: "/media/optimized/DOM_MP4.mp4",
    srcHigh: "/media/DOM_MP4.mp4",
    srcFull: "/media/full/DOM_MP4.mp4",
    poster: "/media/optimized/DOM_MP4.jpg",
    title: "NIGHTCLUB DOM",
  },
  {
    id: "4",
    src: "/media/optimized/hk.mp4",
    srcHigh: "/media/hk.mp4",
    poster: "/media/optimized/hk.jpg",
    title: "HILDÉN & KAIRA",
  },
  {
    id: "5",
    src: "/media/optimized/KLANGI_MP4.mp4",
    srcHigh: "/media/KLANGI_MP4.mp4",
    srcFull: "/media/full/KLANGI_MP4.mp4",
    poster: "/media/optimized/KLANGI_MP4.jpg",
    title: "KLANGI",
  },
  {
    id: "6",
    src: "/media/optimized/WAVE_MP4.mp4",
    srcHigh: "/media/WAVE_MP4.mp4",
    poster: "/media/optimized/WAVE_MP4.jpg",
    title: "WAVE VENTURES",
  },
];
